title:  Irving Emmanuel Gonzalez
tagline:  Blog
author:
  name: 'Irving Emmanuel Gonzalez'
  twitter:  kodamirmo

disqus:
  comments: true
  disqus_shortname: 'kodamirmo'

google-ID: 'UA-50107533-1'

menu:
- {name: 'Acerca', url: 'about.html'}
- {name: 'Contacto', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/kodamirmo'}
- {icon: 'twitter', link: 'https://twitter.com/kodamirmo'}
- {icon: 'instagram', link: 'https://instagram.com/kodamirmo'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/irving-emmanuel-gonzalez-6511a756'}
- {icon: 'envelope', link: 'mailto:irvingemmanuelgg@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
